# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'flutter_iOS_gesture_demo' do

  flutter_application_path = '../flutter_ios_gesture_demo_module'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
end
